/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 6fd8bb43ad293c4de656086dc1fbf9c6)
interface __BaseEnv_Env {
	GOOGLE_CLOUD_PROJECT: string;
	GOOGLE_ACCESS_TOKEN: string;
	ProjectAgent: DurableObjectNamespace<import("./src/server/server").ProjectAgent>;
	SessionAgent: DurableObjectNamespace<import("./src/server/server").SessionAgent>;
	VerifyAgent: DurableObjectNamespace<import("./src/server/server").VerifyAgent>;
	ExploreAgent: DurableObjectNamespace<import("./src/server/server").ExploreAgent>;
	StatementsAgent: DurableObjectNamespace<import("./src/server/server").StatementsAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/server");
		durableNamespaces: "ProjectAgent" | "SessionAgent" | "VerifyAgent" | "ExploreAgent" | "StatementsAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLOUD_PROJECT" | "GOOGLE_ACCESS_TOKEN">> {}
}
