/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 5e94ac884745776db7a4ac6abe05d8f3)
interface __BaseEnv_Env {
	RECORDINGS: R2Bucket;
	GOOGLE_CLOUD_PROJECT: string;
	GOOGLE_ACCESS_TOKEN: string;
	ProjectAgent: DurableObjectNamespace<import("./src/server").ProjectAgent>;
	SessionAgent: DurableObjectNamespace<import("./src/server").SessionAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ProjectAgent" | "SessionAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLOUD_PROJECT" | "GOOGLE_ACCESS_TOKEN">> {}
}
