/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: a1e5fc4fbf49a233009e2bca0f25f7ce)
interface __BaseEnv_Env {
	AI: Ai;
	STT_MODEL: string;
	GOOGLE_CLOUD_PROJECT: string;
	GOOGLE_ACCESS_TOKEN: string;
	VoiceInputAgent: DurableObjectNamespace<import("./src/server").VoiceInputAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "VoiceInputAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "STT_MODEL" | "GOOGLE_CLOUD_PROJECT" | "GOOGLE_ACCESS_TOKEN">> {}
}
