/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: d871d5ad406170581ba0f03d89b7a24e)
interface __BaseEnv_Env {
	AI: Ai;
	GOOGLE_CLOUD_PROJECT: string;
	GOOGLE_ACCESS_TOKEN: string;
	VoiceInputAgent: DurableObjectNamespace<import("./src/server").VoiceInputAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "VoiceInputAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLOUD_PROJECT" | "GOOGLE_ACCESS_TOKEN">> {}
}
